// prettier-ignore
export const VALUES = Object.freeze({
  "01": { value: "01", title: "北海道" },
  "02": { value: "02", title: "青森県" },
  "03": { value: "03", title: "岩手県" },
  "04": { value: "04", title: "宮城県" },
  "05": { value: "05", title: "秋田県" },
  "06": { value: "06", title: "山形県" },
  "07": { value: "07", title: "福島県" },
  "08": { value: "08", title: "茨城県" },
  "09": { value: "09", title: "栃木県" },
  "10": { value: "10", title: "群馬県" },
  "11": { value: "11", title: "埼玉県" },
  "12": { value: "12", title: "千葉県" },
  "13": { value: "13", title: "東京都" },
  "14": { value: "14", title: "神奈川県" },
  "15": { value: "15", title: "新潟県" },
  "16": { value: "16", title: "富山県" },
  "17": { value: "17", title: "石川県" },
  "18": { value: "18", title: "福井県" },
  "19": { value: "19", title: "山梨県" },
  "20": { value: "20", title: "長野県" },
  "21": { value: "21", title: "岐阜県" },
  "22": { value: "22", title: "静岡県" },
  "23": { value: "23", title: "愛知県" },
  "24": { value: "24", title: "三重県" },
  "25": { value: "25", title: "滋賀県" },
  "26": { value: "26", title: "京都府" },
  "27": { value: "27", title: "大阪府" },
  "28": { value: "28", title: "兵庫県" },
  "29": { value: "29", title: "奈良県" },
  "30": { value: "30", title: "和歌山県" },
  "31": { value: "31", title: "鳥取県" },
  "32": { value: "32", title: "島根県" },
  "33": { value: "33", title: "岡山県" },
  "34": { value: "34", title: "広島県" },
  "35": { value: "35", title: "山口県" },
  "36": { value: "36", title: "徳島県" },
  "37": { value: "37", title: "香川県" },
  "38": { value: "38", title: "愛媛県" },
  "39": { value: "39", title: "高知県" },
  "40": { value: "40", title: "福岡県" },
  "41": { value: "41", title: "佐賀県" },
  "42": { value: "42", title: "長崎県" },
  "43": { value: "43", title: "熊本県" },
  "44": { value: "44", title: "大分県" },
  "45": { value: "45", title: "宮崎県" },
  "46": { value: "46", title: "鹿児島県" },
  "47": { value: "47", title: "沖縄県" },
});

export const OPTIONS = Object.entries(VALUES)
  .sort((a, b) => a[0].localeCompare(b[0])) // キー（都道府県コード）でソート
  .map(([key, value]) => {
    return { value: key, title: value.title };
  });
