// prettier-ignore
export const PREFECTURES = Object.freeze({
  "01": { name: "北海道" },
  "02": { name: "青森県" },
  "03": { name: "岩手県" },
  "04": { name: "宮城県" },
  "05": { name: "秋田県" },
  "06": { name: "山形県" },
  "07": { name: "福島県" },
  "08": { name: "茨城県" },
  "09": { name: "栃木県" },
  "10": { name: "群馬県" },
  "11": { name: "埼玉県" },
  "12": { name: "千葉県" },
  "13": { name: "東京都" },
  "14": { name: "神奈川県" },
  "15": { name: "新潟県" },
  "16": { name: "富山県" },
  "17": { name: "石川県" },
  "18": { name: "福井県" },
  "19": { name: "山梨県" },
  "20": { name: "長野県" },
  "21": { name: "岐阜県" },
  "22": { name: "静岡県" },
  "23": { name: "愛知県" },
  "24": { name: "三重県" },
  "25": { name: "滋賀県" },
  "26": { name: "京都府" },
  "27": { name: "大阪府" },
  "28": { name: "兵庫県" },
  "29": { name: "奈良県" },
  "30": { name: "和歌山県" },
  "31": { name: "鳥取県" },
  "32": { name: "島根県" },
  "33": { name: "岡山県" },
  "34": { name: "広島県" },
  "35": { name: "山口県" },
  "36": { name: "徳島県" },
  "37": { name: "香川県" },
  "38": { name: "愛媛県" },
  "39": { name: "高知県" },
  "40": { name: "福岡県" },
  "41": { name: "佐賀県" },
  "42": { name: "長崎県" },
  "43": { name: "熊本県" },
  "44": { name: "大分県" },
  "45": { name: "宮崎県" },
  "46": { name: "鹿児島県" },
  "47": { name: "沖縄県" },
});

export const PREFECTURES_ARRAY = Object.entries(PREFECTURES)
  .sort((a, b) => a[0].localeCompare(b[0])) // キー（都道府県コード）でソート
  .map(([key, value]) => {
    return { value: key, title: value.name };
  });
