export const COMPANY_CONFIGURATION_SCHEMA_VERSION = 1;

export const COMPANY_CONFIGURATION_STATE = "CCB_V1_ACTIVE";

export const COMPANY_STATUS_VALUES = Object.freeze([
  "ACTIVE",
  "SUSPENDED",
  "CLOSED",
]);

export const ROUND_SETTING_VALUES = Object.freeze(["FLOOR", "ROUND", "CEIL"]);

export const ATTENDANCE_SUMMARY_MODE_VALUES = Object.freeze([
  "LABOR_STANDARD",
  "OPERATION_COUNT",
]);

export const SHIFT_TYPE_VALUES = Object.freeze(["DAY", "NIGHT"]);

export const COMPANY_SETTING_TYPE_VALUES = Object.freeze([
  "PROFILE",
  "BILLING",
  "OPERATIONS",
]);

export const COMPANY_CONFIGURATION_ERROR_CODES = Object.freeze({
  INVALID_TYPE: "INVALID_TYPE",
  UNKNOWN_FIELD: "UNKNOWN_FIELD",
  MISSING_FIELD: "MISSING_FIELD",
  INVALID_VALUE: "INVALID_VALUE",
  OUT_OF_RANGE: "OUT_OF_RANGE",
  DUPLICATE_VALUE: "DUPLICATE_VALUE",
  CONFLICT: "CONFLICT",
});
